Change test report layout to modal
flyve-mdm/flyve-mdm-ios-dashboard pull request #45
Opened 2018-06-30 17:24 UTC by hectorerb

Signed-off-by: Hector Rondon <hrondon@teclib.com>

### Changes description
- Change test report layout to modal

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@hectorerb |1|

### References

Closes #32 
Related #N/A
Depends on #N/A

2018-07-01 16:03 UTC, ajsb85 requested changes
Hi, @hectorerb 
Your tests failed on CircleCI

2018-07-10 20:55 UTC, hectorerb commented
Hi @ajsb85 
this PR can be closed, test fails the upload of the ipa file to testflight because the deploy is being made from the develop branch of a fork
![captura de pantalla 2018-07-10 a la s 16 44 47](https://user-images.githubusercontent.com/8787200/42537085-e65ebb16-8461-11e8-8387-8503ce2eeba9.png)

2018-07-11 11:45 UTC, ajsb85 approved these changes

2018-07-11 11:46 UTC, merged

2018-07-11 11:46 UTC, ajsb85 commented
Hi, @hectorerb 
You can bypass the deploy when it's a fork.